import Footer from '@/components/footer/footer';
import Header from '@/components/header/header';
import './globals.css';
import Providers from './providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="pageWrapper">
            <Header />
            <main className="contentWrapper">{children}</main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
