import './globals.css';
import Header from '@/components/header/header';
import I18nProvider from '@/components/I18nProvider/I18nProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Wrap UI in client-side i18n provider */}
        <I18nProvider>
          <Header />
          <main>{children}</main>
        </I18nProvider>
      </body>
    </html>
  );
}
