import Footer from '@/components/footer/footer';
import './globals.css';
import Header from '@/components/header/header';
import I18nProvider from '@/components/I18nProvider/I18nProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Wrap UI in client-side i18n provider */}
       <div className="pageWrapper">
          <I18nProvider>
            <Header />
            <main className="contentWrapper">{children}</main>
            <Footer />
          </I18nProvider>
        </div>
      </body>
    </html>
  );
}
